### ISSUE TITLE
Black pixels appearing between blocs snapped together

### ISSUE THREAD

**Issue by TagliatL** [keijiro/KinoObscurance#14]
Hey, I finally made a[ little project](https://github.com/TagliatL/Obscurance_test) to test this issue out. You can see on the rotating object the black pixels (even if it's pretty subtle). I found out that was because of my Near clipping planes setting being at 0.01, getting it up a little bit remove almost every black pixel but I don't know for sure about it.

**Comment by keijiro** [comment]
Thanks for providing the project.

Yeah, this is a typical case of z-fighting. I found that this reproduces even when Obscurance is turned off... so, I have nothing to do with this problem on the image effect side.

The easiest way to solve the problem is upgrading the project to Unity 5.5. The depth precision is much improved in 5.5 thanks to introducing the reversed-float depth buffer.

https://twitter.com/timsoret/status/768082633821650944

Please feel free to reopen this issue when you meet further problems with Obscurance.
